### PR TITLE
Added doc for inactiveClassName

### PR DESCRIPTION
**Pull request by DanZeuss**
The implementation:
https://github.com/bvaughn/react-highlight-words/pull/27

### CODE REVIEW

**Comment by bvaughn** [comment]
Why a separate PR?

**Comment by DanZeuss** [comment]
I apologize. I'm pretty new on GitHub

**Comment by bvaughn** [comment]
It's okay.

**Comment by bvaughn** [comment]
Just commit this change to your `patch-1` branch and push it as part of PR #27

**Pull request closed without merging**
