### PR TITLE
Add support for React 17

### PR DESCRIPTION
**Pull request by sergei-startsev**
[React 17 was release on October 20th](https://reactjs.org/blog/2020/10/20/react-v17.html).

### CODE REVIEW

**Review by Hossam-Ali — APPROVED** [review]

**Comment by sergei-startsev** [comment]
Is there a chance to merge the changes?

**Comment by jwandrews99** [comment]
I would really like to use this in my react project, is there any chance this PR is going to get merged?

**Comment by 10ARK-StephenKie** [comment]
I would also like to use this component, we are going to be upgrading to React 17.

**Review by rageofflames — APPROVED** [review]

**Comment by pablof300** [comment]
when will this be merged?

**Comment by jwandrews99** [comment]
Everyone be approving but nobody be merging

**Comment by rageofflames** [comment]
Approved, but no permissions to merge, @bvaughn could you please take a look? 🙏 🙈

**Comment by bvaughn** [comment]
I don't have the time to manage projects like this anymore. That's why I disabled issues.

Someone else want to lend a hand?

**Comment by sergei-startsev** [comment]
+1

**Comment by ItzaMi** [comment]
@bvaughn , I haven't maintained an open-source repo before but I'm available to lend a hand if you need it! 👋

**Comment by bvaughn** [comment]
Ideally I'm looking for someone who's comfortable reviewing and merging PRs, testing and creating releases, and publishing them to NPM. I wouldn't really have bandwidth to train or support.

If that's you, let me know and I'll gladly accept the help.

**Comment by sergei-startsev** [comment]
I can volunteer here as well. The package is widely used in several projects I've been working on and forking / replacing it seems a bigger evil to me 😀

**Comment by bvaughn** [comment]
Email me your NPM username.

**Comment by bvaughn** [comment]
Thank you @sergei-startsev

**Comment by sergei-startsev** [comment]
v0.17.0 has been released now.

https://www.npmjs.com/package/react-highlight-words/v/0.17.0

Thanks @bvaughn!

**Comment by jwandrews99** [comment]
Lets go @sergei-startsev GL on the future

**Pull request merged**
