### PR TITLE
Resolve issue #17 - SearchWords proptypes not supporting Regex type

### PR DESCRIPTION
**Pull request by franciscopuyo**

### CODE REVIEW

**Comment by franciscopuyo** [comment]
Could you warn me when its approved and a new release is made? Really thanks

**Comment by bvaughn** [comment]
Hmm, did you test this?

Doesn't look like it would work to me. This library is built on top of another lib, [`highlight-words-core`](https://github.com/bvaughn/highlight-words-core/). It expects an array of strings.

**Comment by franciscopuyo** [comment]
Hi!
Yes I did, in fact, appart of coding the unit test, I'm using it on my current app. Actually what doesn't work is when you try to sanitize the regexp, so when you pass a santize function and regexp as item in the searchWords array it crashes on applying the str.replace. (I figuered it out testing manually in the test site of the repo)

If you want I could fix that too. 

The fact of using regexs is based on that you sometimes don't know all the possibilities you want to highlight. An example would be: 
"I want to highlight all the numbers on the text" (my consciense is speaking)
So, I wont fill an array as [0, 1, 2, 3 .. ], I pass the regex /(0-9)+/ as a "thing" to search for.

**Comment by bvaughn** [comment]
> so when you pass a santize function and regexp as item in the searchWords array it crashes on applying the str.replace. (I figuered it out testing manually in the test site of the repo)

Right. This is the part I was expecting _not_ to work. It sounds like it doesn't.

Before this PR could be merged it would need to actually work, end to end. ([`highlight-words-core`](https://github.com/bvaughn/highlight-words-core/) will need to handle it properly.)

**Pull request closed without merging**
