### PR TITLE
Allow the use of a class for the non highlighted

### PR DESCRIPTION
**Pull request by DanZeuss**
There is a issue that doesn’t allow the user use a specific class for
the elements that has no highlighted texts.

### CODE REVIEW

**Comment by bvaughn** [comment]
`className` is already used for the top level `<span className={className}>`

**Comment by DanZeuss** [comment]
Yes, but it should be applied to the children as well, don you think?

It's creating
```
<span class="my-parent-class">
  <span>xxx</span>
  <mark>y</mark>
  <span>zzz</span>
</span>
```

**Comment by bvaughn** [comment]
> Yes, but it should be applied to the children as well, don you think?

That would limit what you're able to do with the class. 😕  Plus it wouldn't be a backwards-compatible change.

**Comment by DanZeuss** [comment]
how about a new prop name?

**Comment by bvaughn** [comment]
Hm. I guess I don't object, although I think `inactive` is probably better than `nonActive`

The [props docs](https://github.com/bvaughn/react-highlight-words#props) would also need to be updated.

**Comment by DanZeuss** [comment]
I believe that now it's correct @bvaughn

**Comment by DanZeuss** [comment]
Thank you so much Brian. You did a great job!

**Comment by bvaughn** [comment]
Cool. Thanks for the contribution. 😄

I apologize, but last night when you opened this PR I was watching TV with my wife and I didn't give the property name we discussed feature much thought. `activeClassName` isn't the property this is the opposite of. Actually it's the opposite of `highlightClassName` so this property should have been named something more like `unhighlightClassName`. I've gone ahead and renamed after merging your PR and updated the docs.

This feature is out as v0.8.0!

**Pull request merged**
